import Head from 'next/head';
// import Image from "next/image";
import Layout from '@/components/Layout';
import Hero from '@/components/HeroComponent';
import Card from '@/components/BookingStepsComponent';

function newImg() {
  return 'https://source.unsplash.com/random/1600x900';
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex w-full h-full flex-col">
          <Hero
            imageUrl={newImg()}
            title="PARTY AT THE BUNKER!"
            message="Celebrations, corporate events, kids parties and more! Let us host your next event."
          />
          <div className="flex justify-center items-center flex-col p-4 md:p-8">
            <h1 className="text-2xl text-[35px] pb-5 md:pb-10 font-bold">
              BOOK YOUR EVENT
            </h1>
            <Card
              imgUrl={newImg()}
              title="STEP 1: WHERE TO PARTY?"
              message="All of our locations offer a variety of unique party packages and options to create the best event experience for any occasion. Visit our locations page for more information. If you already know the space you want, you're ready for Step 2!"
              onClick={() => {}}
              btnTitle="SEE LOCATIONS & SPACES"
            />
            <Card
              imgUrl={newImg()}
              title="STEP 2: SCHEDULE YOUR PARTY"
              message="Let's get your party scheduled! Start the process by clicking the button below. This will lead you through a series of questions and event options regarding location, number of guests, date and more. Once submitted, our events coordinator will reach out to finalize the booking process."
              onClick={() => {}}
              btnTitle="BOOK NOW"
            />
            <Card
              imgUrl={newImg()}
              title="STEP 3: FOOD & DRINKS"
              message="All of our locations offer a variety of unique party packages and options to create the best event experience for any occasion. Visit our locations page for more information. If you already know the space you want, you're ready for Step 2!"
              onClick={() => {}}
              btnTitle="VIEW MENUS"
            />
          </div>
        </main>
      </Layout>
    </>
  );
}
